name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python from .python-version file
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test
